/* eslint-disable */
/**
 * Generated by scripts/sync-env.js from apps/mobile/.env — do not edit by hand.
 */
export const GENERATED_API_BASE_URL = "https://zygo.onrender.com/api/v1";
export const GENERATED_RAZORPAY_KEY_ID = "rzp_test_SjAKgny2PYhLT6";
