/* eslint-disable */
/**
 * Generated by scripts/sync-env.js from apps/mobile/.env — do not edit by hand.
 */
export const GENERATED_API_BASE_URL = "http://127.0.0.1:4000/api/v1";
export const GENERATED_RAZORPAY_KEY_ID = "rzp_test_SjAKgny2PYhLT6";
