/**
 * Reads apps/mobile/.env and writes src/config/generatedApiUrl.ts.
 * Ensures the API URL is correct at runtime (Metro cannot rely on virtual @env).
 */
const fs = require('fs');
const path = require('path');

const mobileRoot = path.resolve(__dirname, '..');
const envPath = path.join(mobileRoot, '.env');
const outPath = path.join(mobileRoot, 'src', 'config', 'generatedApiUrl.ts');

let api =
  process.env.API_BASE_URL_FALLBACK || 'http://10.0.2.2:4000/api/v1';

if (fs.existsSync(envPath)) {
  const text = fs.readFileSync(envPath, 'utf8');
  for (const line of text.split(/\r?\n/)) {
    const m = line.match(/^\s*API_BASE_URL\s*=\s*(.*)$/);
    if (!m) continue;
    let val = m[1].trim();
    if (
      (val.startsWith('"') && val.endsWith('"')) ||
      (val.startsWith("'") && val.endsWith("'"))
    ) {
      val = val.slice(1, -1);
    }
    if (val.length > 0) {
      api = val.replace(/\/$/, '');
      break;
    }
  }
}

const escaped = JSON.stringify(api);
const contents = `/* eslint-disable */\n/**\n * Generated by scripts/sync-env.js from apps/mobile/.env — do not edit by hand.\n */\nexport const GENERATED_API_BASE_URL = ${escaped};\n`;

fs.writeFileSync(outPath, contents);
console.log('[sync-env] API_BASE_URL ->', api);
