import { StyleSheet } from 'react-native';
import { colors, radii, spacing } from './index';

export const shared = StyleSheet.create({
  flex: { flex: 1, backgroundColor: colors.background },
  scrollContent: {
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.screenTop,
    paddingBottom: spacing.screenBottom,
    flexGrow: 1,
    gap: spacing.stackGap,
  },
  scrollContentAuth: { padding: 24, paddingTop: 48, paddingBottom: 48 },
  list: {
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.screenTop,
    paddingBottom: spacing.screenBottom,
    backgroundColor: colors.background,
    gap: spacing.cardGap,
  },
  listTall: {
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.screenTop,
    paddingBottom: spacing.xxxl + 8,
    backgroundColor: colors.background,
    gap: spacing.cardGap,
  },
  center: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: colors.background,
    paddingHorizontal: spacing.screenX,
  },
  wrap: {
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.screenTop,
    paddingBottom: spacing.screenBottom,
    backgroundColor: colors.background,
    gap: spacing.stackGap,
  },
  wrapWide: {
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.screenTop,
    paddingBottom: spacing.screenBottom,
    backgroundColor: colors.background,
    gap: spacing.stackGap,
  },
  hero: { fontSize: 28, fontWeight: '800', color: colors.text, marginBottom: spacing.sm },
  title: { fontSize: 26, fontWeight: '800', color: colors.text },
  headline: { fontSize: 22, fontWeight: '800', color: colors.text, marginBottom: spacing.lg },
  lead: { color: colors.textSecondary, marginBottom: spacing.xl, lineHeight: 22 },
  sub: { color: colors.textSecondary, lineHeight: 22, marginBottom: spacing.xxl },
  sectionLabel: { fontWeight: '700', color: colors.lavender, marginBottom: spacing.md },
  input: {
    backgroundColor: colors.inputBg,
    borderRadius: radii.md,
    padding: 14,
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    fontSize: 16,
    color: colors.text,
  },
  err: { color: colors.error, marginBottom: spacing.md },
  muted: { color: colors.textMuted },
  meta: { color: colors.textSecondary, marginTop: spacing.xs },
  metaCap: { color: colors.textSecondary, marginTop: spacing.sm, textTransform: 'capitalize' as const },
  emphasis: { color: colors.text, fontWeight: '700' },
  strong: { fontWeight: '700', color: colors.text },
  name: { fontSize: 18, fontWeight: '700', color: colors.text },
  price: { marginTop: spacing.sm, fontWeight: '700', color: colors.primary },
  fare: { fontSize: 32, fontWeight: '800', color: colors.text, marginTop: spacing.sm },
  fareAccent: { fontSize: 28, fontWeight: '800', color: colors.primary },
  total: { marginTop: spacing.sm, fontWeight: '800', color: colors.primary },
  devHint: { marginTop: spacing.xxl, fontSize: 11, color: colors.textMuted },
  spacer: { height: spacing.lg },
  mt: { marginTop: spacing.lg },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing.sm },
  chip: {
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.chipBorder,
  },
  chipActive: {
    backgroundColor: colors.chipActiveBg,
    borderColor: colors.primary,
  },
  chipText: { fontWeight: '600', color: colors.textSecondary, fontSize: 14 },
  chipTextActive: { color: colors.lavender },
  hint: { color: colors.textMuted, fontSize: 12, marginBottom: spacing.xs },
  label: { fontWeight: '600', marginBottom: spacing.sm, color: colors.lavender },
  centerText: { padding: spacing.xxl, textAlign: 'center', color: colors.textMuted },
  badge: {
    alignSelf: 'flex-start',
    marginTop: spacing.md,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: radii.pill,
    backgroundColor: colors.badge,
    color: colors.badgeText,
    fontWeight: '600',
    overflow: 'hidden',
  },
  cardMb: { marginBottom: spacing.lg },
  cardArea: { marginTop: spacing.xxl, gap: spacing.lg },
  desc: { fontSize: 16, color: colors.textSecondary, lineHeight: 22 },
  otp: {
    backgroundColor: colors.inputBg,
    borderRadius: radii.lg,
    paddingVertical: 16,
    paddingHorizontal: 18,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.inputBorder,
    fontSize: 24,
    letterSpacing: 8,
    fontWeight: '700',
    textAlign: 'center',
    color: colors.primary,
  },
  block: { marginTop: spacing.xl },
  h: { fontWeight: '700', marginBottom: spacing.sm, color: colors.lavender },
  line: { color: colors.textSecondary, marginBottom: spacing.xs },
  orderNum: { fontSize: 20, fontWeight: '800', color: colors.text },
  stat: { marginTop: spacing.md, fontWeight: '600', textTransform: 'capitalize', color: colors.text },
  footer: {
    padding: spacing.lg,
    borderTopWidth: 1,
    borderColor: colors.footerBorder,
    backgroundColor: colors.footer,
  },
  qtyBtn: {
    width: 36,
    height: 36,
    borderRadius: radii.sm,
    backgroundColor: colors.primarySoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  qtyTxt: { fontSize: 18, fontWeight: '700', color: colors.primary },
  addBtn: {
    marginTop: spacing.sm,
    paddingVertical: spacing.sm,
    paddingHorizontal: 14,
    borderRadius: radii.pill,
    backgroundColor: colors.primarySoft,
    alignSelf: 'flex-start',
  },
  addBtnText: { color: colors.primary, fontWeight: '700' },
  cartLinkText: { color: colors.primary, fontWeight: '700' },
  vehicleChip: {
    paddingVertical: 12,
    paddingHorizontal: spacing.lg,
    borderRadius: radii.pill,
    backgroundColor: colors.chip,
    borderWidth: 1,
    borderColor: colors.chipBorder,
  },
  vehicleChipOn: { backgroundColor: colors.primary, borderColor: colors.primary },
  vehicleChipTxt: { fontWeight: '600', color: colors.textSecondary },
  vehicleChipTxtOn: { color: colors.text, fontWeight: '700' },
  row: { flexDirection: 'row', alignItems: 'center' },
  itemName: { fontSize: 16, fontWeight: '700', color: colors.text },
  itemMeta: { color: colors.textSecondary, marginTop: spacing.xs },
  rname: {
    fontSize: 18,
    fontWeight: '800',
    paddingHorizontal: spacing.screenX,
    paddingTop: spacing.md,
    paddingBottom: 0,
    color: colors.text,
  },
  iname: { fontWeight: '700', color: colors.text },
  iprice: { color: colors.textSecondary, marginTop: spacing.xs },
  qtyNum: { fontWeight: '700', minWidth: 24, textAlign: 'center', color: colors.text },
  qtyRow: { flexDirection: 'row', alignItems: 'center', gap: spacing.sm },
  empty: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.xxl,
    gap: spacing.lg,
    backgroundColor: colors.background,
  },
  cartLink: { alignSelf: 'flex-end', marginBottom: spacing.sm },
  half: { flex: 1 },
  section: { marginTop: spacing.xxl, marginBottom: spacing.sm, fontWeight: '700', color: colors.lavender },
  profileName: { fontSize: 22, fontWeight: '800', color: colors.text },
  phone: { color: colors.textSecondary, marginTop: spacing.xs },
  addrLabel: { fontWeight: '700', color: colors.text },
  addrLine: { color: colors.textSecondary, marginTop: spacing.xs },
  box: { marginVertical: spacing.lg },
  mapBox: {
    height: 200,
    borderRadius: radii.lg,
    overflow: 'hidden',
    marginBottom: spacing.md,
    borderWidth: 1,
    borderColor: colors.cardBorder,
  },
  map: { flex: 1 },
  listTitle: { fontWeight: '700', fontSize: 16, color: colors.text },
  vehicleRow: { flexDirection: 'row', gap: 10, marginBottom: spacing.lg, flexWrap: 'wrap' },
  cardTitle: { fontWeight: '700', fontSize: 16, marginBottom: spacing.sm, color: colors.text },
  cardMuted: { color: colors.textSecondary, lineHeight: 20 },
});
